name: slack-workflow-result

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: action-slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: nahyun
        only_mention_fail: 이나현_T4146
        fields: repo, message, commit, author, action, eventName, ref, workflow, job, took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
